CREATE DATABASE INVENTORY;

USE INVENTORY;

CREATE TABLE SUPPLIER
(SID CHAR(5),
SNAME VARCHAR(20) NOT NULL,
SADD VARCHAR(30) NOT NULL,
SCITY CHAR(5),
SPHONE VARCHAR(15),
EMAIL VARCHAR(20)
);

ALTER TABLE SUPPLIER 
ALTER COLUMN SID CHAR(5) NOT NULL;

ALTER TABLE SUPPLIER 
ADD CONSTRAINT S1 PRIMARY KEY (SID);

ALTER TABLE SUPPLIER
ADD CONSTRAINT S2 DEFAULT 'DELHI' FOR SCITY;

ALTER TABLE SUPPLIER
ADD CONSTRAINT S3 UNIQUE(SPHONE);

SELECT * FROM SUPPLIER;

CREATE TABLE PRODUCT
(PID CHAR(5) NOT NULL,
PDESC VARCHAR(40) NOT NULL,
PRICE INT,
CATEGORY CHAR(2),
SID CHAR(5)
);

ALTER TABLE PRODUCT
ADD CONSTRAINT P1 PRIMARY KEY (PID);

ALTER TABLE PRODUCT
ADD CONSTRAINT P2 CHECK (PRICE>0);


ALTER TABLE PRODUCT
ADD CONSTRAINT P3 CHECK (CATEGORY IN ('IT','HA','HC'));

ALTER TABLE PRODUCT
ADD CONSTRAINT P4 FOREIGN KEY (SID) REFERENCES SUPPLIER(SID);


CREATE TABLE STOCK
(PID CHAR(5) NOT NULL,
SQTY INT CHECK (SQTY>=0),
ROL INT CHECK (ROL>0),
MOQ INT CHECK (MOQ>=5)
);

ALTER TABLE PRODUCT
ADD CONSTRAINT ST1 FOREIGN KEY (PID) REFERENCES PRODUCT(PID);

CREATE TABLE CUSTOMER
(CID CHAR(5) NOT NULL,
CNAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR (40)NOT NULL,
CITY VARCHAR (10) NOT NULL,
PHONE VARCHAR (15) NOT NULL,
EMAIL VARCHAR (20) NOT NULL,
DOB DATE CHECK (DOB<'1-JAN-2000')
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT C1 PRIMARY KEY (CID);

CREATE TABLE ORDERS
(OID CHAR (5) NOT NULL,
ODATE DATE,
PID CHAR(5),
CID CHAR(5),
OQTY INT CHECK (OQTY >=1)
);

ALTER TABLE ORDERS
ADD CONSTRAINT O1 FOREIGN KEY (PID) REFERENCES PRODUCT (PID);

ALTER TABLE ORDERS
ADD CONSTRAINT O2 FOREIGN KEY (CID) REFERENCES CUSTOMER (CID);

******************************INSERTION OF RECORDS*****************************

CREATE PROCEDURE ADDSUPLIER @SID AS CHAR(5),@SNAME AS VARCHAR(20),@SADD AS VARCHAR(30),@SCITY AS CHAR(5),@SPHONE AS VARCHAR(15),@EMAIL VARCHAR(20)
AS
BEGIN
     INSERT INTO SUPPLIER
	 VALUES(@SID,@SNAME,@SADD,@SCITY,@SPHONE,@EMAIL);

     SELECT * FROM SUPPLIER WHERE SID = @SID;

END;

ADDSUPLIER 'S0006','TRENDS','BANNERGHATTA ROAD','BANGALORE','9741597466','CONTACT@TRENDS.COM';

SELECT * FROM SUPPLIER;



CREATE PROCEDURE ADDPRO @PID AS CHAR(5),@PDESC AS VARCHAR(40),@PRICE AS INT,@CATEGORY AS CHAR(2),@SID AS VARCHAR(5)
AS
BEGIN
     INSERT INTO PRODUCT
	 VALUES(@PID,@PDESC,@PRICE,@CATEGORY,@SID);

     SELECT * FROM PRODUCT WHERE PID = @PID;

END;

ADDPRO 'P0015','WALLET',900,'HC','S0006';

SELECT * FROM PRODUCT;




CREATE PROCEDURE ADDCUST @CID AS CHAR(5),@CNAME AS VARCHAR(20),@ADDRESS AS VARCHAR(40),@CITY AS VARCHAR(10),@PHONE AS VARCHAR(15),@EMAIL AS VARCHAR(20),@DOB AS DATE
AS
BEGIN
     INSERT INTO CUSTOMER
	 VALUES(@CID,@CNAME,@ADDRESS,@CITY,@PHONE,@EMAIL,@DOB);

     SELECT * FROM CUSTOMER WHERE CID = @CID;

END;

ADDCUST 'C0005','JOY','16,NEELADRI ROAD','BANGALORE','9741597455','JOY@GMAIL.COM','8-JAN-1996';

SELECT * FROM CUSTOMER;




CREATE PROCEDURE ADDORDER @OID AS CHAR(5),@ODATE AS DATE,@PID AS CHAR(5),@CID AS CHAR(5),@OQTY AS INT
AS
BEGIN
     INSERT INTO ORDERS
	 VALUES(@OID,@ODATE,@PID,@CID,@OQTY);

     SELECT * FROM ORDERS WHERE OID = @OID;

END;

CREATE PROCEDURE ADDORDER @OID AS CHAR(5),@PID AS CHAR(5),@CID AS CHAR(5),@OQTY AS INT
AS
BEGIN
     INSERT INTO ORDERS
	 VALUES(@OID,GETDATE(),@PID,@CID,@OQTY);

     SELECT * FROM ORDERS WHERE OID = @OID;

END;


DROP PROCEDURE ADDORDER;
ADDORDER 'O0007','P0004','C0002',3;

SELECT * FROM ORDERS;


